### ISSUE TITLE
problem in scrapping algorithms section

### ISSUE THREAD

**Issue by eldiago** [CuriousLearner/GeeksForGeeksScrapper#5]
Scraping link no: 244 Link:  http://www.geeksforgeeks.org/count-number-of-bits-to-be-flipped-to-convert-a-to-b/
Traceback (most recent call last):
  File "g4g.py", line 106, in <module>
    scrape_category(categoryUrl)
  File "g4g.py", line 82, in scrape_category
    link_soup = BeautifulSoup(requests.get(link).text)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 65, in get
    return request('get', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 567, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 646, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for ' http://www.geeksforgeeks.org/count-number-of-bits-to-be-flipped-to-convert-a-to-b/'

**Comment by CuriousLearner** [comment]
@eldiago Resolved.

**Comment by eldiago** [comment]
thanx mate...

**Comment by CuriousLearner** [comment]
:+1:
